language: go
sudo: required
services:
- docker
env:
- SH="docker exec -t domain_pecker bash -c"
before_install:
- docker run --detach --name domain_pecker -v $(pwd):/travis -w /travis -e GOPATH='/travis' golang:1.11-stretch tail -f /dev/null
- docker ps
install:
- $SH "rm -rf /travis/*"
script: skip
after_failure:
- curl -X POST -d 'message="home-api-node build failed"' https://${HOME_API_USER}:${HOME_API_AUTH}@${REMOTE_SERVER}/api/pushover
after_success:
- curl -X POST -d 'message="home-api-node build successful"' https://${HOME_API_USER}:${HOME_API_AUTH}@${REMOTE_SERVER}/api/pushover
before_deploy:
- openssl enc -aes-256-cbc -iv "${SSL_IV}" -K "${SSL_KEY}" -out id_rsa -in .travis/secrets.enc -d
- $SH "go get -v github.com/mike-seagull/domain_pecker"
- which ssh-agent || ( sudo apt-get update -qy && apt-get install --no-install-recommends
  -qfy openssh-client git )
- mkdir -p ~/.ssh
- mv id_rsa ~/.ssh/id_rsa
- sudo chmod 600 ~/.ssh/id_rsa
- ssh-keyscan -H $REMOTE_SERVER > ~/.ssh/known_hosts
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
