---
language: minimal
sudo: required
services:
  - docker
env:
  global:
    - TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
    - SH="docker exec -t $TRAVIS_REPO_NAME bash -c"
install: skip
script:
  - docker run --detach --name $TRAVIS_REPO_NAME -v $(pwd):/travis -w /travis -e GOPATH='/travis' golang:1.13-stretch tail -f /dev/null
  - docker ps
  - $SH "rm -rf /travis/*"
before_deploy:
  - $SH "apt-get update -qy && apt-get install --no-install-recommends -qfy zip"
  - $SH "go get github.com/$TRAVIS_REPO_SLUG"
  - $SH "go run mage.go package"
deploy:
  provider: lambda
  function_name: $TRAVIS_REPO_NAME
  region: "us-east-1"
  role: $ROLE_ARN
  runtime: go1.x
  handler_name: main
  on:
    branch: master
notifications:
  pushover:
    api_key: ""
    users: ""
    enabled: false